export const GET_MOVIE_THEATER = 'GET_MOVIE_THEATER';

export const GET_ARRAY_MOVIE = 'GET_ARRAY_MOVIE';

export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE';


export const GET_INFOR_CALENDAR_THEATER_MOVIE = "GET_INFOR_CALENDAR_THEATER_MOVIE";

export const GET_INFOR_TICKET_ROOM = "GET_INFOR_TICKET_ROOM";
export const BOOKING = "BOOKING" 
